=== BeenaBalakrishna/yggdrasil/yggdrasil/.ygg_metaschema.json
{"$id":"http://json-schema.org/draft-07/schema#","$schema":"http://json-schema.org/draft-07/schema#","default":true,"definitions":{"nonNegativeInteger":{"minimum":0,"type":"integer"},"nonNegativeIntegerDefault0":{"allOf":[{"$ref":"#/definitions/nonNegativeInteger"},{"default":0}]},"schemaArray":{"items":{"$ref":"#"},"minItems":1,"type":"array"},"simpleTypes":{"enum":["array","boolean","integer","null","number","object","string","1darray","bytes","class","complex","float","function","instance","int","ndarray","obj","ply","scalar","schema","uint","unicode"]},"stringArray":{"default":[],"items":{"type":"string"},"type":"array","uniqueItems":true}},"properties":{"$comment":{"type":"string"},"$id":{"format":"uri-reference","type":"string"},"$ref":{"format":"uri-reference","type":"string"},"$schema":{"format":"uri","type":"string"},"additionalItems":{"$ref":"#"},"additionalProperties":{"$ref":"#"},"allOf":{"$ref":"#/definitions/schemaArray"},"anyOf":{"$ref":"#/definitions/schemaArray"},"args":{"description":"Arguments required to recreate a class instance.","type":"object"},"class":{"description":"One or more classes that the object should be an instance of.","oneOf":[{"type":"class"},{"items":{"type":"class"},"minItems":1,"type":"array"}]},"const":true,"contains":{"$ref":"#"},"contentEncoding":{"type":"string"},"contentMediaType":{"type":"string"},"default":true,"definitions":{"additionalProperties":{"$ref":"#"},"default":{},"type":"object"},"dependencies":{"additionalProperties":{"anyOf":[{"$ref":"#"},{"$ref":"#/definitions/stringArray"}]},"type":"object"},"description":{"type":"string"},"else":{"$ref":"#"},"enum":{"items":true,"type":"array"},"examples":{"items":true,"type":"array"},"exclusiveMaximum":{"type":"number"},"exclusiveMinimum":{"type":"number"},"format":{"type":"string"},"if":{"$ref":"#"},"items":{"anyOf":[{"$ref":"#"},{"$ref":"#/definitions/schemaArray"}],"default":true},"length":{"description":"Number of elements in the 1D array.","minimum":1,"type":"number"},"maxItems":{"$ref":"#/definitions/nonNegativeInteger"},"maxLength":{"$ref":"#/definitions/nonNegativeInteger"},"maxProperties":{"$ref":"#/definitions/nonNegativeInteger"},"maximum":{"type":"number"},"minItems":{"$ref":"#/definitions/nonNegativeIntegerDefault0"},"minLength":{"$ref":"#/definitions/nonNegativeIntegerDefault0"},"minProperties":{"$ref":"#/definitions/nonNegativeIntegerDefault0"},"minimum":{"type":"number"},"multipleOf":{"exclusiveMinimum":0,"type":"number"},"not":{"$ref":"#"},"oneOf":{"$ref":"#/definitions/schemaArray"},"pattern":{"format":"regex","type":"string"},"patternProperties":{"additionalProperties":{"$ref":"#"},"default":{},"propertyNames":{"format":"regex"},"type":"object"},"precision":{"description":"The size (in bits) of each item.","minimum":1,"type":"number"},"properties":{"additionalProperties":{"$ref":"#"},"default":{},"type":"object"},"propertyNames":{"$ref":"#"},"readOnly":{"default":false,"type":"boolean"},"required":{"$ref":"#/definitions/stringArray"},"shape":{"description":"Shape of the ND array in each dimension.","items":{"minimum":1,"type":"integer"},"type":"array"},"subtype":{"description":"The base type for each item.","enum":["bytes","complex","float","int","uint","unicode"],"type":"string"},"then":{"$ref":"#"},"title":{"type":"string"},"type":{"anyOf":[{"$ref":"#/definitions/simpleTypes"},{"items":{"$ref":"#/definitions/simpleTypes"},"minItems":1,"type":"array","uniqueItems":true}]},"uniqueItems":{"default":false,"type":"boolean"},"units":{"description":"Physical units.","type":"string"}},"title":"Ygg meta-schema for data type schemas","type":["object","boolean"]}

=== BeenaBalakrishna/yggdrasil/cis_interface/metaschema/datatypes/schemas/ply.json
{
	"definitions": {
		"colors": {
			"precision": 8,
			"subtype": "uint",
			"type": "1darray"
		},
		"coords": {
			"precision": 32,
			"subtype": "float",
			"type": "1darray"
		},
		"indexes": {
			"precision": 32,
			"subtype": "int",
			"type": "1darray"
		}
	},
	"description": "A mapping container for Ply 3D data.",
	"properties": {
		"edge": {
			"description": "Map of edge properties.",
			"properties": {
				"blue": {
					"$ref": "#/definitions/colors"
				},
				"green": {
					"$ref": "#/definitions/colors"
				},
				"red": {
					"$ref": "#/definitions/colors"
				},
				"vertex1": {
					"$ref": "#/definitions/indexes"
				},
				"vertex2": {
					"$ref": "#/definitions/indexes"
				}
			},
			"required": [
				"vertex1",
				"vertex2"
			],
			"type": "object"
		},
		"face": {
			"description": "Map of face properties.",
			"properties": {
				"vertex_indices": {
					"items": {
						"$ref": "#/definitions/indexes"
					},
					"type": "array"
				}
			},
			"required": [
				"vertex_indices"
			],
			"type": "object"
		},
		"material": {
			"description": "Map of material properties.",
			"properties": {},
			"type": "object"
		},
		"vertex": {
			"description": "Map of vertex properties.",
			"properties": {
				"blue": {
					"$ref": "#/definitions/colors"
				},
				"green": {
					"$ref": "#/definitions/colors"
				},
				"red": {
					"$ref": "#/definitions/colors"
				},
				"x": {
					"$ref": "#/definitions/coords"
				},
				"y": {
					"$ref": "#/definitions/coords"
				},
				"z": {
					"$ref": "#/definitions/coords"
				}
			},
			"required": [
				"x",
				"y",
				"z"
			],
			"type": "object"
		}
	},
	"required": [
		"vertex",
		"face",
		"edge"
	],
	"title": "ply",
	"type": "object"
}
